<!DOCTYPE html>
<html lang="he" dir="rtl">
<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>דמוקריטוס | אנשי הרוח של יוון העתיקה</title><link rel="stylesheet" href="../styles.css" />
  <link rel="stylesheet" href="person.css" /></head>
<body><nav class="site-nav" aria-label="ניווט ראשי"><a class="nav-brand" href="../index.html">← חזרה לדף הבית</a><div class="nav-links"><a href="../gallery.html">גלריה כללית</a><a href="#sources">מקורות</a></div></nav><main class="home-shell">
<header class="person-hero"><div><p class="eyebrow">פילוסופיה · אטומיזם · קדם־סוקרטים</p><div class="person-title-row"><h1>דמוקריטוס</h1><span class="life-dates">כ־460–370 לפנה״ס</span></div><p class="person-lead">דמוקריטוס היה פילוסוף יווני שנודע כאחד ממפתחי תורת האטומים: הרעיון שכל החומר מורכב מחלקיקים זעירים הנעים בתוך ריק.</p><div class="hero-facts"><span><strong>תקופה</strong>המאה ה־5–4 לפנה״ס</span><span><strong>תחום</strong>פילוסופיה וטבע</span><span><strong>תרומה</strong>אטומים וריק</span><span><strong>ודאות</strong>רעיונותיו ידועים ממסורות וקטעים</span></div></div><figure class="person-image-card"><img src="../assets/images/people/democritus.jpg" alt="פסל המיוחס לדמוקריטוס" loading="eager" /><figcaption>פסל המיוחס לדמוקריטוס. מקור: Wikimedia Commons. צילום: Yair-haklai. רישיון: CC BY-SA 4.0.</figcaption></figure></header>
<nav class="quick-nav" aria-label="תפריט פנימי"><a href="#identity">תעודת זהות</a><a href="#biography">ביוגרפיה</a><a href="#works">רעיונות</a><a href="#world">רקע היסטורי</a><a href="#legacy">מורשת</a><a href="#facts">הידעת?</a><a href="#sources">מקורות</a></nav>
<section id="identity" class="person-section"><p class="eyebrow">1 · תעודת זהות</p><h2>מי הוא דמוקריטוס במבט מהיר?</h2><div class="identity-grid"><div class="info-card"><strong>שם יווני</strong><span>Δημόκριτος</span></div><div class="info-card"><strong>שם באנגלית</strong><span>Democritus</span></div><div class="info-card"><strong>שנות חיים</strong><span>כ־460–370 לפנה״ס</span></div><div class="info-card"><strong>תחום</strong><span>פילוסופיה, טבע, אטומיזם, אתיקה</span></div></div></section>
<section id="biography" class="person-section"><p class="eyebrow">2 · ביוגרפיה</p><h2>מי היה דמוקריטוס?</h2><p>דמוקריטוס נולד באבדרה שבצפון יוון ונחשב לאחד ההוגים החשובים של הפילוסופיה הקדם־סוקרטית. המסורת קושרת אותו למסעות לימוד רחבים ולסקרנות יוצאת דופן כלפי טבע העולם.</p><p>הוא המשיך ופיתח את רעיונותיו של לאוקיפוס, ובמרכז מחשבתו עמדה השאלה ממה עשוי העולם. תשובתו הייתה נועזת במיוחד: המציאות מורכבת מאטומים ומריק.</p></section>
<section id="works" class="person-section"><p class="eyebrow">3 · רעיונות מרכזיים</p><h2>האטום, הריק ומבנה החומר</h2><div class="card-grid"><article class="work-card"><h3>האטום – רעיון ששינה את העולם</h3><p>המילה היוונית <strong>ἄτομος</strong> פירושה “שאינו ניתן לחלוקה”. דמוקריטוס, וככל הנראה גם מורו לאוקיפוס, הציעו שכל החומר מורכב מחלקיקים זעירים כאלה.</p><button class="modal-button" type="button" id="openSource">📜 מסמך מקור</button><div class="work-meta"><span>ἄτομος</span><span>אטום</span><span>בלתי ניתן לחלוקה</span></div></article><article class="work-card"><h3>אטומים וריק</h3><p>לפי דמוקריטוס, האטומים נעים בתוך ריק, ושוני בצורה, בגודל ובסידור שלהם יוצר את כל הדברים בעולם. כיום ידוע שהאטום ניתן לחלוקה, אך השם העתיק נשאר בשימוש במדע.</p><div class="work-meta"><span>ריק</span><span>חומר</span><span>תנועה</span></div></article></div></section>
<section id="world" class="person-section"><p class="eyebrow">4 · רקע היסטורי</p><h2>הרקע ההיסטורי</h2><div class="card-grid"><div class="info-card"><span class="card-icon">🏛</span><strong>אבדרה</strong><span>עיר יוונית בצפון הים האגאי, המזוהה במיוחד עם דמוקריטוס.</span></div><div class="info-card"><span class="card-icon">🧩</span><strong>חיפוש אחר יסודות</strong><span>הוגים יוונים רבים ניסו להבין מהו החומר הבסיסי שממנו עשוי העולם.</span></div><div class="info-card"><span class="card-icon">⚛</span><strong>לאוקיפוס</strong><span>דמוקריטוס פיתח כנראה מסורת אטומיסטית שהחלה אצל לאוקיפוס.</span></div><div class="info-card"><span class="card-icon">📜</span><strong>מקורות חלקיים</strong><span>רבים מכתביו לא שרדו בשלמותם, ולכן הידע עליו מגיע ממסורות מאוחרות.</span></div></div></section>
<section id="legacy" class="person-section"><p class="eyebrow">5 · מורשת והשפעה</p><h2>מורשתו של דמוקריטוס</h2><div class="legacy-grid"><div class="legacy-card"><span class="card-icon">⚛</span><strong>רעיון האטום</strong><span>שמו נקשר לאחת התפיסות החשובות בהיסטוריה של חקר החומר.</span></div><div class="legacy-card"><span class="card-icon">🔬</span><strong>מדע מודרני</strong><span>גם לאחר שהמדע גילה שהאטום ניתן לחלוקה, המונח העתיק נשאר מרכזי בפיזיקה ובכימיה.</span></div><div class="legacy-card"><span class="card-icon">🧠</span><strong>פילוסופיה של הטבע</strong><span>דמוקריטוס הציע הסבר טבעי לעולם ללא צורך במיתוס כגורם מרכזי.</span></div><div class="legacy-card"><span class="card-icon">🌍</span><strong>עד ימינו</strong><span>רעיון האטומים ממשיך להיות אחד הסיפורים הגדולים של המעבר מפילוסופיה למדע.</span></div></div></section>
<section id="facts" class="person-section"><p class="eyebrow">6 · הידעת?</p><h2>עובדות מעניינות</h2><div class="facts-grid"><div class="fact-card"><strong>לא דמוקרטיה</strong><span>למרות הדמיון בשם, דמוקריטוס אינו קשור ישירות למושג “דמוקרטיה”. שתי המילים חולקות את המרכיב היווני <strong>דמוס</strong> — “העם” — אך החלק השני שלהן שונה.</span></div><div class="fact-card"><strong>שם ששרד אלפי שנים</strong><span>המונח “אטום”, שמקורו ב־<strong>ἄτομος</strong>, נטבע לפני יותר מ־2,400 שנה ועדיין נמצא בשימוש יומיומי במדע המודרני.</span></div><div class="fact-card"><strong>הפילוסוף הצוחק</strong><span>במסורת מאוחרת דמוקריטוס כונה לעיתים “הפילוסוף הצוחק”.</span></div></div></section>
<section id="sources" class="person-section"><p class="eyebrow">7 · מקורות</p><h2>מקורות וקריאה נוספת</h2><div class="card-grid"><div class="info-card"><strong>מקורות עתיקים</strong><span>קטעי דמוקריטוס ועדויות מאוחרות על האטומיסטים היוונים.</span></div><div class="info-card"><strong>מחקר מודרני</strong><span>מחקרים על האטומיזם היווני, דמוקריטוס ולאוקיפוס.</span></div><div class="info-card"><strong>תמונה</strong><span>מקור: Wikimedia Commons. צילום: Yair-haklai. רישיון: CC BY-SA 4.0.</span></div></div></section>
<footer class="person-footer"><a href="heraclitus.html">← הרקליטוס</a><a href="../index.html">דף הבית</a><span>הבא בהמשך: היפוקרטס</span></footer></main>
<div class="source-modal" id="sourceModal" role="dialog" aria-modal="true" aria-labelledby="sourceTitle"><div class="modal-panel"><div class="modal-head"><h2 id="sourceTitle">פרגמנטים של דמוקריטוס</h2><button class="modal-close" type="button" id="closeSource">סגור ✕</button></div><div class="tab-buttons"><button class="tab-button is-active" type="button" data-tab="he">📜 עברית</button><button class="tab-button" type="button" data-tab="en">🇬🇧 English</button></div><section class="tab-panel is-active" id="tab-he"><p class="source-note">רוב כתביו של דמוקריטוס לא שרדו בשלמותם. הקטעים כאן הם עיבודים קצרים בעברית לרעיונות המיוחסים לו במסורת: אטומים, טבע, הכרה ואושר.</p><div class="source-text"><p>“לפי המוסכמה יש מתוק, לפי המוסכמה יש מר; אך באמת קיימים אטומים וריק.”</p><p>“הדברים נוצרים מתוך התחברות האטומים, ונפרדים כאשר האטומים מתפזרים.”</p><p>“לא הגוף ולא העושר הם שעושים את האדם מאושר, אלא יושר המחשבה ושלוות הנפש.”</p><p>“הטבע והחינוך דומים זה לזה: החינוך משנה את האדם ויוצר בו טבע חדש.”</p></div></section><section class="tab-panel" id="tab-en"><p class="source-note english-text">Most of Democritus’ writings survive only in fragments and later reports. The selections below are short interpretive renderings of ideas associated with him.</p><div class="source-text english-text"><p>“By convention there is sweet, by convention bitter; in reality there are atoms and void.”</p><p>“Things come into being when atoms combine, and pass away when they separate.”</p><p>“Neither body nor wealth makes a person happy, but right-mindedness and serenity.”</p><p>“Nature and education are similar: education transforms the person and creates a new nature.”</p></div></section></div></div>
  <script src="person.js"></script>
</body></html>